- name: install nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
    - name: stop nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
    - name: enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes