- name : variables from file
  hosts: web
  become: yes
  vars_files:
    - vars.yaml
    - vars1.yaml
  vars_prompt:
    - name: yourname
      prompt: "Enter the yourname"
      private: false  
  tasks:
    - name: print variable
      ansible.builtin.debug:
        msg: " Printing Statement for {{ nam }}: {{ myvar }} + {{ val }} + {{ yourname }}"