- name:
  hosts: web
  become: yes
  vars:
    myvar: "Hello World"
    nam : "Chintu"
  tasks:
    - name : print variable
      ansible.builtin.debug:
        msg: " Printing Statement for {{ nam }}: {{ myvar }}"