- name:
  hosts: web
  become: yes
  vars:
    myvar: "Hello World"
    name : "Chintu"
  tasks:
    - name : print variable
      ansible.builtin.debug:
        msg: " Printing Statement for {{ name }}: {{ myvar }}"